#!/usr/bin/env bash
set -e

GITHUB_USER=ezzatron

if [[ -d "$HOME/git/hub/$GITHUB_USER/dotfiles" ]]; then
    echo "Pulling $GITHUB_USER/dotfiles..."
    pushd "$HOME/git/hub/$GITHUB_USER/dotfiles"
    git pull
    popd
else
    echo "Cloning $GITHUB_USER/dotfiles..."
    git clone "https://github.com/$GITHUB_USER/dotfiles.git" "$HOME/git/hub/$GITHUB_USER/dotfiles"
fi
