com.microsoft.VSCode .md all
com.microsoft.VSCode .xml all
com.microsoft.VSCode public.json all
com.microsoft.VSCode public.plain-text all
com.microsoft.VSCode public.python-script all
com.microsoft.VSCode public.shell-script all
com.microsoft.VSCode public.source-code	all
com.microsoft.VSCode public.text all
com.microsoft.VSCode public.unix-executable all
