#!/usr/bin/env zsh
# outputs the Git repo slug (e.g. ezzatron/dotfiles)

if ! URL="$(git config --get remote.origin.url)"; then
  return 1
fi

if [[ "$URL" =~ [:/]([^/:]+/[^/]+)\.git$ ]]; then
  echo "${match[1]}"
elif [[ "$1" == '--fuzzy' ]]; then
  echo "???/$(basename "$(pwd)")"
else
  return 1
fi
