#!/usr/bin/env zsh
# nvm auto-loading

local nvmrc_path
nvmrc_path="$(nvm_find_nvmrc)"

if [ -n "$nvmrc_path" ]; then
  local nvmrc_node_version
  nvmrc_node_version=$(nvm version "$(cat "${nvmrc_path}")")

  if [ "$nvmrc_node_version" = "N/A" ]; then
    nvm install &>/dev/null
  elif [ "$nvmrc_node_version" != "$(nvm version)" ]; then
    nvm use &>/dev/null
  fi
elif [ -n "$(PWD=$OLDPWD nvm_find_nvmrc)" ] && [ "$(nvm version)" != "$(nvm version system)" ]; then
  nvm use system &>/dev/null
fi
