#!/usr/bin/env zsh
# defines a custom Powerlevel10k prompt segment for Telepresence
#
# displays the current Telepresence container

if [[ -n "$TELEPRESENCE_CONTAINER" ]]; then
  p10k segment -i '󰄙 ' -b 1 -f 15 -t "$TELEPRESENCE_CONTAINER"
fi
